AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: local invoke template.

Resources:
  LineBot:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/line-bot
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /callback
            Method: post